name: Java CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory contents
        run: ls -l target

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: target/*.jar
