name: Java CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    # Build with Maven
    - name: Build with Maven
      run: mvn clean package

    # Upload the JAR as an artifact
    - name: Archive JAR
      uses: actions/upload-artifact@v3
      with:
        name: java-web-app
        path: target/*.jar
